<?php
require "controllers/get-all-users.php";
?>
<main class="container py-5">
    <h1 class="my-5">Liste des utilisateurs</h1>
    <a href="index.php?route=create" class="btn btn-primary">Créer un utilisateur</a>
    <table class="table table-striped mt-5">
        <thead>
            <tr>
                <th>#</th>
                <th>Nom</th>
                <th>Email</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($users as $i => $user): ?>
                <tr>
                    <td><?= $user['id'] ?></td>
                    <td><?= $user['username'] ?></td>
                    <td><?= $user['email'] ?></td>
                    <td>
                        <a class="btn btn-info mx-1" href="index.php?route=show&user=<?= $user['id'] ?>"><span class="bi bi-eye"></span></a>
                        <a class="btn btn-success mx-1" href="index.php?route=update&user=<?= $user['id'] ?>"><span class="bi bi-pencil"></span></a>
                        <a class="btn btn-danger mx-1 deletebtn"><span class="bi bi-trash3"></span></a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</main>

<div class="modal fade" id="deletemodal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Delete Data</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

                <form action="index.php?route=delete&user=<?= $user['id'] ?>" method="POST">

                <div class="modal-body">

                    <input type="hidden" name="update_id" id="update_id">
                
                    <h4> Do you want to Delete this Data ??</h4>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                    <button type="submit" name="deletedata" class="btn btn-primary">Delete Data</button>
                </div>
            </form>
        
        </div>
    </div>
</div>

<script src="/features/jquery.min.js">/</script>
<script src="/features/popper.min.js"></script>
<script src="/features/bootstrap.min.js"></script>

<script>
$(document).ready(function ()
{
   $('.deletebtn').on('click', function()
    {
        $('#deletemodal').modal('show');


            $tr = $(this).closest('tr');

            var data = $tr.children("td").map(function()
            {
                return $(thos).text();
            }).get;

            console.log(data);

            $('#update_id').val(data[0]);
    });
});
</script>