<main class="container py-5">
    <h1 class="my-5">Liste des utilisateurs</h1>
    <a href="index.php?route=create" class="btn btn-primary">Créer un utilisateur</a>
    <table class="table table-striped mt-5">
        <thead>
            <tr>
                <th>#</th>
                <th>Nom</th>
                <th>Email</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    Id de l'utilisateur 1
                </td>
                <td>
                    Nom de l'utilisateur 1
                </td>
                <td>
                    Email de l'utilisateur 1
                </td>
                <td>
                    <a class="btn btn-info mx-1" href="index.php?route=show&user=1"><span class="bi bi-eye"></span></a>
                    <a class="btn btn-success mx-1" href="index.php?route=update&user=1"><span class="bi bi-pencil"></span></a>
                    <a class="btn btn-danger mx-1" href="index.php?route=delete&user=1"><span class="bi bi-trash3"></span></a>
                </td>
            </tr>
            <tr>
                <td>
                    Id de l'utilisateur 2
                </td>
                <td>
                    Nom de l'utilisateur 2
                </td>
                <td>
                    Email de l'utilisateur 2
                </td>
                <td>
                    <a class="btn btn-info mx-1" href="index.php?route=show&user=2"><span class="bi bi-eye"></span></a>
                    <a class="btn btn-success mx-1" href="index.php?route=update&user=2"><span class="bi bi-pencil"></span></a>
                    <a class="btn btn-danger mx-1" href="index.php?route=delete&user=2"><span class="bi bi-trash3"></span></a>
                </td>
            </tr>
        </tbody>
    </table>
</main>