<?php
require "controllers/get-user.php";
?>
<main class="container py-5">
    <a href="index.php?route=list">Retour à la liste</a>
    <h1 class="my-5">Modifier un utilisateur</h1>
    <form method="post" action="controllers/update-user.php?user_id=<?= $user['id'] ?>">
        <fieldset class="form-group mb-2">
            <label class="form-label" for="user-id">Id de l'utilisateur</label>
            <input class="form-control" type="text" name="user_id" id="user_id" value="<?= $user['id'] ?>" readonly disabled required>
        </fieldset>
        <fieldset class="form-group mb-2">
            <label class="form-label" for="name">Nom de l'utilisateur</label>
            <input class="form-control" type="text" name="name" id="name" value="<?= $user['username'] ?>" required>
        </fieldset>
        <fieldset class="form-group mb-2">
            <label class="form-label" for="email">Email de l'utilisateur</label>
            <input class="form-control" type="email" name="email" id="email" value="<?= $user['email'] ?>" required>
        </fieldset>
        <fieldset class="form-group mb-5">
            <label class="form-label" for="job">Sélectionnez l'emploi</label>
            <select class="form-select" id="job" name="job">
                <option selected><?= $user['job'] ?></option>
                <option value="1">Journaliste</option>
                <option value="2">Conservatrice de musée</option>
                <option value="3">Riche</option>
                <option value="4">Vétéran</option>
                <option value="5">Lycéen</option>
            </select>
        </fieldset>
        <fieldset class="form-group">
            <button class="btn btn-primary" type="submit">Enregistrer</button>
        </fieldset>
    </form>
</main>