<main class="container py-5">
    <h1 class="my-5">Liste des utilisateurs</h1>
    <a href="index.php?route=create_user" class="btn btn-primary">Créer un utilisateur</a>
    <table class="table table-striped mt-5">
        <thead>
            <tr>
                <th>#</th>
                <th>Prénom</th>
                <th>Nom</th>
                <th>Email</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($data as $i => $user): ?>
                <tr>
                    <td><?= $user->getId() ?></td>
                    <td><?= $user->getFirstName() ?></td>
                    <td><?= $user->getLastName() ?></td>
                    <td><?= $user->getEmail() ?></td>
                    <td>
                        <a class="btn btn-info mx-1" href="index.php?route=show_user&user=<?= $user->getId() ?>"><span class="bi bi-eye"></span></a>
                        <a class="btn btn-success mx-1" href="index.php?route=update_user&user=<?= $user->getId() ?>"><span class="bi bi-pencil"></span></a>
                        <a class="btn btn-danger mx-1 deletebtn" href="index.php?route=delete_user&user=<?= $user->getId() ?>"><span class="bi bi-trash3"></span></a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</main>