<?php
require "models/Users.php";
require "models/Posts.php";
require "models/Categories.php";
require "managers/PostManager.php";
require "managers/UserManager.php";
require "managers/CategoryManager.php";
$user = new User("user1","password1","email1","role1",date("Y-m-d H:i:s"));
//$post = new Post("title1","exerpt1","content1",1,"now");
//$category = new Category("title1","exerpt1");
//echo "<pre>";
//var_dump($post);
//echo "</pre>";
//echo "<pre>";
//var_dump($category);
//echo "</pre>";
//$post->addCategory($category);
//$category->addPost($post);
//echo "<pre>";
//var_dump($post);
//echo "</pre>";
//echo "<pre>";
//var_dump($category);
//echo "</pre>";
$console = new CategoryManager();
$categories= $console->findAll();
echo "<pre>";
var_dump($categories);
echo "</pre>";