<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@100;200;300;400;500;600;700;800&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="assets/styles/css/style.css?v=<?php echo filemtime('assets/styles/css/style.css'); ?>">
        <title>Accueil</title>
    </head>
    <?php require "header.phtml"; ?>
    <body>
        <h1>This is the homepage</h1>
    </body>
</html>